#!/usr/bin/env bash
# Build, verify or check the prebuilt micro-wake-word library, libhapaneld_mww.so.
#
# The library compiles the vendored TFLite Micro subset, which took two to three minutes per ABI on
# every clean build. It changes rarely, so it is built once with the pinned NDK, stripped, committed
# under app/src/main/jniLibs/<abi>/ and recorded in tools/wakeword/prebuilt/manifest.txt together with
# a digest of every input that determines its bytes.
#
#   build-prebuilt.sh build     rebuild every ABI, install the stripped libraries, rewrite the manifest
#   build-prebuilt.sh verify    no toolchain needed: the committed libraries and the current sources
#                               must match the manifest (run by CI on every change)
#   build-prebuilt.sh check     rebuild into a temporary directory and require byte-identical libraries
#                               (run by CI when the sources or the libraries change)
#
# Requires, for build and check: ANDROID_HOME with ndk;27.0.12077973 and cmake;3.22.1 installed.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
readonly REPO_ROOT
readonly NDK_VERSION=27.0.12077973
readonly CMAKE_VERSION=3.22.1
readonly ANDROID_API=26
readonly ABIS=(arm64-v8a armeabi-v7a x86_64)
readonly LIBRARY=libhapaneld_mww.so
readonly SOURCE_DIR=app/src/main/cpp/microwakeword
readonly MANIFEST="$REPO_ROOT/tools/wakeword/prebuilt/manifest.txt"

die() { printf 'build-prebuilt: %s\n' "$*" >&2; exit 1; }

# Every file whose bytes can change the library, plus the toolchain pins, hashed in a stable order.
source_digest() {
  (
    cd "$REPO_ROOT"
    printf 'ndk %s\ncmake %s\napi %s\n' "$NDK_VERSION" "$CMAKE_VERSION" "$ANDROID_API"
    find "$SOURCE_DIR" tools/wakeword/prebuilt/CMakeLists.txt tools/wakeword/build-prebuilt.sh -type f -print0 \
      | LC_ALL=C sort -z | xargs -0 sha256sum
  ) | sha256sum | cut -d' ' -f1
}

file_digest() { sha256sum "$1" | cut -d' ' -f1; }

build_into() {
  local out=$1 work abi
  local sdk="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-}}"
  [ -n "$sdk" ] || die 'ANDROID_HOME is not set'
  local ndk="$sdk/ndk/$NDK_VERSION" cmake_bin="$sdk/cmake/$CMAKE_VERSION/bin"
  [ -f "$ndk/build/cmake/android.toolchain.cmake" ] || die "NDK $NDK_VERSION is not installed under $sdk"
  [ -x "$cmake_bin/cmake" ] && [ -x "$cmake_bin/ninja" ] || die "cmake $CMAKE_VERSION is not installed under $sdk"
  local strip="$ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip"
  work="$(mktemp -d)"
  trap 'rm -rf "$work"' RETURN
  local digest
  digest="$(source_digest)"
  for abi in "${ABIS[@]}"; do
    local build_id
    build_id="$(printf '%s %s' "$digest" "$abi" | sha256sum | cut -c1-40)"
    # Map the checkout and build directories out of the compiled strings (__FILE__ in TFLite Micro's
    # error reporting) so the bytes do not depend on where the tree or the build directory lives.
    local prefix_map="-ffile-prefix-map=$REPO_ROOT/= -ffile-prefix-map=$work/$abi/="
    "$cmake_bin/cmake" -G Ninja -S "$REPO_ROOT/tools/wakeword/prebuilt" -B "$work/$abi" \
      -DCMAKE_MAKE_PROGRAM="$cmake_bin/ninja" \
      -DCMAKE_TOOLCHAIN_FILE="$ndk/build/cmake/android.toolchain.cmake" \
      -DANDROID_ABI="$abi" -DANDROID_PLATFORM="android-$ANDROID_API" -DANDROID_STL=c++_static \
      -DCMAKE_BUILD_TYPE=Release -DMWW_BUILD_ID="$build_id" \
      -DCMAKE_C_FLAGS="$prefix_map" -DCMAKE_CXX_FLAGS="$prefix_map" > "$work/$abi.configure.log" \
      || { cat "$work/$abi.configure.log" >&2; die "configure failed for $abi"; }
    "$cmake_bin/ninja" -C "$work/$abi" hapaneld_mww > "$work/$abi.build.log" \
      || { tail -40 "$work/$abi.build.log" >&2; die "build failed for $abi"; }
    mkdir -p "$out/$abi"
    "$strip" --strip-unneeded -o "$out/$abi/$LIBRARY" "$work/$abi/microwakeword/$LIBRARY"
    printf 'built %s %s\n' "$abi" "$(file_digest "$out/$abi/$LIBRARY")"
  done
}

write_manifest() {
  local abi
  {
    printf '# Generated by tools/wakeword/build-prebuilt.sh build. Do not edit.\n'
    printf 'sources %s\n' "$(source_digest)"
    for abi in "${ABIS[@]}"; do
      printf '%s %s\n' "$abi" "$(file_digest "$REPO_ROOT/app/src/main/jniLibs/$abi/$LIBRARY")"
    done
  } > "$MANIFEST"
}

manifest_value() {
  local key=$1 value
  value="$(awk -v k="$key" '$1 == k { print $2 }' "$MANIFEST")"
  [ -n "$value" ] || die "manifest has no $key entry"
  printf '%s' "$value"
}

verify() {
  [ -f "$MANIFEST" ] || die "missing $MANIFEST"
  local failed=0 abi lib gradle_ndk gradle_min_sdk
  # The app build owns the NDK and minimum SDK. A change there must rebuild these libraries too.
  gradle_ndk="$(sed -nE 's/^[[:space:]]*ndkVersion = "([^"]+)"$/\1/p' "$REPO_ROOT/app/build.gradle.kts")"
  gradle_min_sdk="$(sed -nE 's/^[[:space:]]*minSdk = ([0-9]+)$/\1/p' "$REPO_ROOT/app/build.gradle.kts")"
  if [ "$gradle_ndk" != "$NDK_VERSION" ] || [ "$gradle_min_sdk" != "$ANDROID_API" ]; then
    printf 'build-prebuilt: app/build.gradle.kts uses NDK %s and minSdk %s, but the prebuilt libraries use NDK %s and API %s\n' \
      "${gradle_ndk:-?}" "${gradle_min_sdk:-?}" "$NDK_VERSION" "$ANDROID_API" >&2
    failed=1
  fi
  if [ "$(source_digest)" != "$(manifest_value sources)" ]; then
    printf 'build-prebuilt: the wake-word sources changed since the prebuilt libraries were built; run tools/wakeword/build-prebuilt.sh build\n' >&2
    failed=1
  fi
  for abi in "${ABIS[@]}"; do
    lib="$REPO_ROOT/app/src/main/jniLibs/$abi/$LIBRARY"
    if [ ! -f "$lib" ] || [ -L "$lib" ]; then
      printf 'build-prebuilt: missing prebuilt %s\n' "$lib" >&2; failed=1; continue
    fi
    if [ "$(file_digest "$lib")" != "$(manifest_value "$abi")" ]; then
      printf 'build-prebuilt: %s does not match the manifest\n' "$lib" >&2; failed=1
    fi
  done
  [ "$failed" = 0 ] || exit 1
  printf 'prebuilt wake-word libraries match their manifest and sources\n'
}

case "${1:-}" in
  build)
    out="$(mktemp -d)"
    build_into "$out"
    for abi in "${ABIS[@]}"; do
      install -D -m 0644 "$out/$abi/$LIBRARY" "$REPO_ROOT/app/src/main/jniLibs/$abi/$LIBRARY"
    done
    rm -rf "$out"
    write_manifest
    verify
    ;;
  verify)
    verify
    ;;
  check)
    verify
    out="$(mktemp -d)"
    build_into "$out"
    failed=0
    for abi in "${ABIS[@]}"; do
      if [ "$(file_digest "$out/$abi/$LIBRARY")" != "$(manifest_value "$abi")" ]; then
        printf 'build-prebuilt: rebuilding %s from source gave different bytes than the committed library\n' "$abi" >&2
        failed=1
      fi
    done
    rm -rf "$out"
    [ "$failed" = 0 ] || exit 1
    printf 'rebuilt wake-word libraries are byte-identical to the committed prebuilts\n'
    ;;
  *)
    die 'usage: build-prebuilt.sh build|verify|check'
    ;;
esac
