#!/usr/bin/env bash
printf 'aapt %s\n' "$*" >> "${MOCK_CALL_LOG:?MOCK_CALL_LOG is required}"
printf "package: name='%s' versionCode='220' versionName='0.9.2-rc3'\n" "${MOCK_RELEASE_PACKAGE:-io.github.maxlyth.hapaneld}"
