#!/usr/bin/env python3
"""Generate ha-paneld's adaptive-icon foreground (VectorDrawable) + a PNG preview.

Design: a 4:3 wall-panel device (hard corners, thin bezel, no home button) whose screen shows the
official Home Assistant house mark (kept modest — a panel that runs HA, not an HA app). The HA mark
paths come from the official asset in scripts/assets/ha-logo-source.svg (home-assistant.io); only the
mark is blue. Run: python3 scripts/gen-icon.py
"""
import os, re

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, "scripts/assets/ha-logo-source.svg")
FG = os.path.join(HERE, "app/src/main/res/drawable/ic_launcher_foreground.xml")
PREVIEW = os.path.join(HERE, "docs/icon-preview.png")

PANEL = (14, 24, 80, 60, 4); PANEL_FILL = "#37474F"
SCREEN = (18, 28, 72, 52, 2); SCREEN_FILL = "#0E1620"
MARK_W = 240.0          # the HA mark occupies ~0..240 of the source viewBox
MARK_PX = 30.0          # rendered size on the screen (smaller = less "HA app")


def rr(x, y, w, h, r):
    return (f"M{x+r},{y} h{w-2*r} a{r},{r} 0 0 1 {r},{r} v{h-2*r} a{r},{r} 0 0 1 {-r},{r} "
            f"h{-(w-2*r)} a{r},{r} 0 0 1 {-r},{-r} v{-(h-2*r)} a{r},{r} 0 0 1 {r},{-r} z")


def mark_paths():
    svg = open(SRC).read()
    return [p for p in re.findall(r'<path[^>]*?/>', svg) if ('#18BCF2' in p or '#F2F4F9' in p)]


def placement():
    sc = MARK_PX / MARK_W
    px, py, pw, ph, _ = SCREEN
    sx, sy, sw, sh, _ = SCREEN
    tx = sx + (sw - MARK_W * sc) / 2
    ty = sy + (sh - MARK_W * sc) / 2
    return sc, tx, ty


def vector_xml():
    sc, tx, ty = placement()
    paths = [p.replace('fill="', 'android:fillColor="').replace('/>', ' />') for p in mark_paths()]
    paths = [re.sub(r'<path', '        <path xmlns:android="http://schemas.android.com/apk/res/android"', p) for p in paths]
    # simpler: rebuild path elements with android namespace
    md = []
    for p in mark_paths():
        fill = re.search(r'fill="([^"]+)"', p).group(1)
        d = re.search(r'd="([^"]+)"', p).group(1)
        md.append(f'        <path android:fillColor="{fill}" android:pathData="{d}" />')
    marks = "\n".join(md)
    return (f'<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    android:width="108dp" android:height="108dp"\n'
            f'    android:viewportWidth="108" android:viewportHeight="108">\n'
            f'    <!-- Generated by scripts/gen-icon.py: wall-panel device + official HA mark on screen. -->\n'
            f'    <path android:fillColor="{PANEL_FILL}" android:pathData="{rr(*PANEL)}" />\n'
            f'    <path android:fillColor="{SCREEN_FILL}" android:pathData="{rr(*SCREEN)}" />\n'
            f'    <group android:translateX="{tx:.2f}" android:translateY="{ty:.2f}" '
            f'android:scaleX="{sc:.4f}" android:scaleY="{sc:.4f}">\n{marks}\n    </group>\n</vector>\n')


def composite_svg():
    sc, tx, ty = placement()
    marks = "\n".join(mark_paths())
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="108" height="108" viewBox="0 0 108 108">\n'
            f'<rect width="108" height="108" rx="24" fill="#FFFFFF"/>\n'
            f'<path d="{rr(*PANEL)}" fill="{PANEL_FILL}"/>\n'
            f'<path d="{rr(*SCREEN)}" fill="{SCREEN_FILL}"/>\n'
            f'<g transform="translate({tx:.2f},{ty:.2f}) scale({sc:.4f})">\n{marks}\n</g>\n</svg>\n')


if __name__ == "__main__":
    open(FG, "w").write(vector_xml())
    print("wrote", FG)
    try:
        import cairosvg
        cairosvg.svg2png(bytestring=composite_svg().encode(), write_to=PREVIEW, output_width=512, output_height=512)
        print("preview ->", PREVIEW)
    except Exception as e:
        print("preview skipped:", e)
